name: Build & Publish Docker Image

env:
  REGISTRY: https://git.rjm.ie
  IMAGE_NAME: ${{ github.repository }}

on:
  push:
    branches: ['main', 'master']
    paths:
      # We need to include everything then exclude the files we don't want to trigger the workflow
      - '**'
      - '!docs/**'
      - '!LICENSE.md'
      - '!README.md'
      - '!.prettierignore'
      - '!.prettierrc'
      - '!eslint.config.js'
      - '!.github/workflows/run-tests.yml'
      - '!.github/workflows/test-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - run: |
        # 1. Create the 'docker' group if it doesn't exist
        # The GID (e.g., 999) must match the primary group of the Docker socket on the HOST.
        # We find the host socket's group ID by statting the mounted file:
        HOST_DOCKER_GID=$(stat -c '%g' /var/run/docker.sock)
        
        # 2. Add the 'docker' group to the container with the HOST's GID
        # This is key: it maps the container 'docker' group to the host's actual group ID.
        if ! getent group docker ; then
          groupadd -g $HOST_DOCKER_GID docker
          echo "Added 'docker' group with GID $HOST_DOCKER_GID"
        fi

        # 3. Add the current container user to the 'docker' group
        # We check if the user is already in the group before attempting to add
        CURRENT_USER=$(whoami)
        if ! id -nG "$CURRENT_USER" | grep -qw "docker"; then
          usermod -aG docker $CURRENT_USER
          echo "Added user $CURRENT_USER to the 'docker' group."
        fi

        # Optional: Verify the current user's groups
        echo "Current user's groups after modification:"
        id

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=long
            type=match,pattern=main
            type=raw,value=latest,enable={{is_default_branch}}
          flavor: |
            latest=auto

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
